version: '2'
services:
    crti-app:
        image: crti
        external_links:
            - crti-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/crti
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    crti-postgresql:
        extends:
            file: postgresql.yml
            service: crti-postgresql
